# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20170914_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='index',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
